class TestModel {

  // id: map['id'] ?? '',
  //     ca: map['ca'] ?? '',
  //     docID: map['docID'] ?? '',
  //     notice: map['notice'] ?? '',
  //     employeeId: map['employeeId'] ?? '',
  //     employeeName: map['employeeName'] ?? '',
  //     peaNo: map['pea_no'] ?? '',
  //     cusName: map['cus_name'] ?? '',
  //     line: map['line'] ?? '',
  //     status: map['status'] ?? '',
  //     statusTxt: map['status_txt'] ?? '',
  //     type: map['type'] ?? '',
  //     typeTxt: map['type_txt'] ?? '',
  //     tel: map['tel'] ?? '',
  //     address: map['address'] ?? '',
  //     invoice: map['invoice'] ?? '',
  //     arrears: map['arrears'] ?? '',
  //     images: map['images'] ?? '',
  //     readNumber: map['readNumber'] ?? '',
  //     lat: map['lat'] ?? '',
  //     lng: map['lng'] ?? '',
  //     paymentDate: map['paymentDate'] ?? '',
  //     dataStatus: map['dataStatus'] ?? '',
  //     refnoti_date: map['refnoti_date'] ?? '',
  //     timestamp: map['timestamp'] ?? '',
  //     userId: map['user_id'] ?? '',
  //     importDate: map['import_date'] ?? '',
  //     image_befor_wmmr: map['image_befor_wmmr'] ?? '',
  
}